version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/web-app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: SepAdmin
      POSTGRES_PASSWORD: FcGoldfinger
      POSTGRES_DB: SepDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: